modLoader="javafml"
loaderVersion="[47,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/HudCompass/issues"

[[mods]]
modId="hudcompass"
version="${file.jarVersion}"
displayName="HUD Compass"
logoFile="logo.png"
authors="gigaherz"
displayURL="https://github.com/gigaherz/HudCompass"
description='''
See where you go
'''

[[dependencies.hudcompass]]
   modId="forge"
   mandatory=true
   versionRange="[47.1.3,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.hudcompass]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.20.2)"
   ordering="NONE"
   side="BOTH"
[[dependencies.hudcompass]]
   modId="journeymap"
   mandatory=false
   versionRange="[5.9.8,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.hudcompass]]
   modId="curios"
   mandatory=false
   versionRange="[${curios_version},)"
   ordering="NONE"
   side="BOTH"